(
var patch = UnoSynthPatch();
patch.name = "Moody bass";
patch.kvps[90]=0;patch.kvps[44]=0;patch.kvps[19]=0;patch.kvps[23]=99.0;patch.kvps[103]=0;patch.kvps[67]=48.0;patch.kvps[72]=0;patch.kvps[91]=0;patch.kvps[45]=58.0;patch.kvps[17]=61.0;patch.kvps[12]=106.0;patch.kvps[71]=0;patch.kvps[70]=0;patch.kvps[47]=76.0;patch.kvps[105]=64;patch.kvps[18]=64.0;patch.kvps[46]=71.0;patch.kvps[73]=0;patch.kvps[22]=90.0;patch.kvps[20]=5.0;patch.kvps[7]=64.0;patch.kvps[102]=127;patch.kvps[81]=88.0;patch.kvps[75]=0;patch.kvps[104]=48.0;patch.kvps[76]=0;patch.kvps[74]=0;patch.kvps[78]=0;patch.kvps[13]=127;patch.kvps[66]=117.0;patch.kvps[15]=127;patch.kvps[14]=0;patch.kvps[106]=0;patch.kvps[89]=0;patch.kvps[77]=0;patch.kvps[92]=0;patch.kvps[26]=73.0;patch.kvps[16]=26.0;patch.kvps[24]=0;patch.kvps[80]=115.0;patch.kvps[68]=4.0;patch.kvps[49]=127;patch.kvps[69]=6.0;patch.kvps[27]=79.0;patch.kvps[25]=64;patch.kvps[21]=63.0;patch.kvps[5]=0;
UnoSynth.saveSpecificPatch(patch);
)